### ISSUE TITLE
.gradle/caches/transforms-2/files-2.1/3169be8d56a9e4c03db106c1e19e99ac/jetified-SimpleSearchView-0.1.4/res/values/values.xml:5:5-33:25: AAPT: error: resource attr/backIconAlpha (aka com.estyle:attr/backIconAlpha) not found.     

### ISSUE THREAD

**Issue by priyankvadhiya** [Ferfalk/SimpleSearchView#26]

**Comment by marbat87** [comment]
same issue for me

**Comment by flaringapp** [comment]
Same for me

**Comment by flaringapp** [comment]
Fixed in version **0.1.5**
P.S. Workaround for old versions:
Append these 2 lines
```
<attr name="backIconAlpha"/>
<attr name="iconsAlpha"/>
```
into your _attrs_ file

**Comment by diegoalvis** [comment]
@flaringapp  are not those params related to the opacity? so  Should not they have a `float` format instead `dimension` format?

**Comment by vkotovv** [comment]
@diegoalvis You're right, I've submitted related MR: #32

**Comment by vkotovv** [comment]
This issue can be closed now, was fixed in 0.1.5

**Comment by moetouban** [comment]
@vkotovv this is still happening in 0.1.6
in these attributes 
        <attr format="dimension" name="backIconAlpha"/>
        <attr format="dimension" name="iconsAlpha"/>
